name: angular_translate
version: 0.6.1
description: I18n Library for AngularDart
author: ANDO Yasushi <andyjpn@gmail.com>
homepage: https://github.com/technohippy/angular-translate.dart
dependencies:
  browser: ">=0.9.1 <0.9.2"
  angular: ">=0.9.10 <1.0.0"
